### ISSUE TITLE
KeyError: 'PHP'

### ISSUE THREAD

**Issue by s1lviu** [fedoco/apple-slicer#12]
```
Sales in Philippines (PH)
	Quantity	Product	Amount	Exchange Rate	Amount in USD
Traceback (most recent call last):
  File "/Users/silviu/apple-slicer/./slicer.py", line 286, in <module>
    print_sales_by_corporation(sales, currencies, args.no_subtotals, args.only_subtotals, args.selected_corporations)
  File "/Users/silviu/apple-slicer/./slicer.py", line 237, in print_sales_by_corporation
    exchange_rate, tax_factor = currency_data[country_currency]
KeyError: 'PHP'
```

🤔

**Comment by fedoco** [comment]
`PHP` is the currency code for Philippine Peso. This error indicates that you had sales in the Philippines but there is no corresponding line for that currency in `financial_report.csv`.
